"""Baseline schema

Revision ID: 23fd4d2169a9
Revises: 
Create Date: 2026-06-28 21:25:41.967078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23fd4d2169a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_version', sa.Column('version_label', sa.String(length=50), nullable=False))
    op.add_column('dataset_version', sa.Column('version_number', sa.String(length=20), nullable=True))
    op.add_column('dataset_version', sa.Column('data_level', sa.String(length=10), nullable=True))
    op.add_column('dataset_version', sa.Column('base_path', sa.String(), nullable=True))
    op.add_column('dataset_version', sa.Column('released_at', sa.Date(), nullable=True))
    op.add_column('dataset_version', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('dataset_version', 'processing_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_unique_constraint(None, 'dataset_version', ['version_label'])
    op.drop_column('dataset_version', 'release_date')
    op.drop_column('dataset_version', 'version_code')
    op.add_column('instrument', sa.Column('instrument_code', sa.String(length=50), nullable=False))
    op.alter_column('instrument', 'mission_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('instrument', 'instrument_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('instrument', 'instrument_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_column('instrument', 'wavelength_end')
    op.drop_column('instrument', 'wavelength_start')
    op.drop_column('instrument', 'resolution')
    op.add_column('instrument_spec_libs', sa.Column('wavelength_min_nm', sa.Float(), nullable=True))
    op.add_column('instrument_spec_libs', sa.Column('wavelength_max_nm', sa.Float(), nullable=True))
    op.add_column('instrument_spec_libs', sa.Column('spectral_resolution_nm', sa.Float(), nullable=True))
    op.add_column('instrument_spec_libs', sa.Column('pixel_count', sa.Integer(), nullable=True))
    op.add_column('instrument_spec_libs', sa.Column('calibration_version', sa.String(length=100), nullable=True))
    op.alter_column('instrument_spec_libs', 'instrument_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('instrument_spec_libs', 'detector_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.create_unique_constraint(None, 'instrument_spec_libs', ['instrument_id'])
    op.drop_column('instrument_spec_libs', 'spectral_channels')
    op.drop_column('instrument_spec_libs', 'calibration_source')
    op.add_column('measurement_clean', sa.Column('measurement_index', sa.Integer(), nullable=False))
    op.add_column('measurement_clean', sa.Column('time_utc', sa.DateTime(), nullable=True))
    op.add_column('measurement_clean', sa.Column('measurement_count', sa.Integer(), nullable=True))
    op.add_column('measurement_clean', sa.Column('operation_mode', sa.String(length=10), nullable=True))
    op.add_column('measurement_clean', sa.Column('measurement_type', sa.String(length=50), nullable=True))
    op.add_column('measurement_clean', sa.Column('force_reset_status', sa.Integer(), nullable=True))
    op.add_column('measurement_clean', sa.Column('delay_time_us', sa.Float(), nullable=True))
    op.add_column('measurement_clean', sa.Column('number_of_pulses', sa.Integer(), nullable=True))
    op.add_column('measurement_clean', sa.Column('x_factor', sa.Integer(), nullable=True))
    op.add_column('measurement_clean', sa.Column('laser_pump_current_a', sa.Integer(), nullable=True))
    op.add_column('measurement_clean', sa.Column('prr_hz', sa.Integer(), nullable=True))
    op.add_column('measurement_clean', sa.Column('on_off_status', sa.Integer(), nullable=True))
    op.alter_column('measurement_clean', 'file_info_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.drop_column('measurement_clean', 'created_at')
    op.drop_column('measurement_clean', 'shot_number')
    op.add_column('measurement_raw', sa.Column('measurement_index', sa.Integer(), nullable=False))
    op.add_column('measurement_raw', sa.Column('time_utc', sa.DateTime(), nullable=True))
    op.add_column('measurement_raw', sa.Column('measurement_count', sa.Integer(), nullable=True))
    op.add_column('measurement_raw', sa.Column('operation_mode', sa.String(length=10), nullable=True))
    op.add_column('measurement_raw', sa.Column('measurement_type', sa.String(length=5), nullable=True))
    op.add_column('measurement_raw', sa.Column('force_reset_status', sa.Integer(), nullable=True))
    op.add_column('measurement_raw', sa.Column('delay_time_us', sa.Float(), nullable=True))
    op.add_column('measurement_raw', sa.Column('number_of_pulses', sa.Integer(), nullable=True))
    op.add_column('measurement_raw', sa.Column('x_factor', sa.Integer(), nullable=True))
    op.add_column('measurement_raw', sa.Column('laser_pump_current_a', sa.Integer(), nullable=True))
    op.add_column('measurement_raw', sa.Column('prr_hz', sa.Integer(), nullable=True))
    op.add_column('measurement_raw', sa.Column('on_off_status', sa.Integer(), nullable=True))
    op.alter_column('measurement_raw', 'file_info_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.drop_column('measurement_raw', 'is_background')
    op.drop_column('measurement_raw', 'is_valid_plasma')
    op.drop_column('measurement_raw', 'shot_number')
    op.drop_column('measurement_raw', 'created_at')
    op.alter_column('mission', 'mission_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('mission', 'mission_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('mission', 'organization',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('mission', 'launch_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('nist_lines', 'element',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('nist_lines', 'wavelength_nm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('observation', sa.Column('logical_identifier', sa.String(), nullable=True))
    op.add_column('observation', sa.Column('observation_code', sa.String(length=100), nullable=True))
    op.add_column('observation', sa.Column('observation_number', sa.Integer(), nullable=True))
    op.add_column('observation', sa.Column('sub_index', sa.Integer(), nullable=True))
    op.add_column('observation', sa.Column('pds_version_id', sa.String(length=10), nullable=True))
    op.add_column('observation', sa.Column('purpose', sa.String(length=100), nullable=True))
    op.alter_column('observation', 'observation_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('observation', 'session_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('observation', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('observation', 'stop_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('observation', 'information_model_version',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('observation', 'processing_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_unique_constraint(None, 'observation', ['observation_code'])
    op.create_unique_constraint(None, 'observation', ['logical_identifier'])
    op.drop_column('observation', 'xml_label_name')
    op.add_column('observation_file_info', sa.Column('base_file_name', sa.String(length=255), nullable=True))
    op.add_column('observation_file_info', sa.Column('md5_checksum_raw', sa.String(length=32), nullable=True))
    op.add_column('observation_file_info', sa.Column('md5_checksum_clean', sa.String(length=32), nullable=True))
    op.add_column('observation_file_info', sa.Column('file_size_bytes_raw', sa.BigInteger(), nullable=True))
    op.add_column('observation_file_info', sa.Column('file_size_bytes_clean', sa.BigInteger(), nullable=True))
    op.add_column('observation_file_info', sa.Column('xml_label_name', sa.String(length=255), nullable=True))
    op.add_column('observation_file_info', sa.Column('creation_datetime', sa.DateTime(), nullable=True))
    op.add_column('observation_file_info', sa.Column('storage_path_clean', sa.String(), nullable=True))
    op.alter_column('observation_file_info', 'file_info_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('observation_file_info', 'observation_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'observation_file_info', ['observation_id'])
    op.drop_column('observation_file_info', 'md5_checksum')
    op.drop_column('observation_file_info', 'file_size_bytes')
    op.drop_column('observation_file_info', 'file_name')
    op.add_column('observation_session', sa.Column('date_folder', sa.String(length=10), nullable=True))
    op.add_column('observation_session', sa.Column('target_description', sa.String(), nullable=True))
    op.add_column('observation_session', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('observation_session', 'dataset_version_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('observation_session', 'observation_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('observation_session', 'orbit_number')
    op.drop_column('observation_session', 'session_type')
    op.alter_column('spectral_data_clean', 'measurement_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('spectral_data_clean', 'wavelength_nm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('spectral_data_clean', 'intensity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('spectral_data_raw', sa.Column('response_count', sa.Integer(), nullable=False))
    op.alter_column('spectral_data_raw', 'measurement_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('spectral_data_raw', 'wavelength_nm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('spectral_data_raw', 'intensity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spectral_data_raw', sa.Column('intensity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('spectral_data_raw', 'wavelength_nm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('spectral_data_raw', 'measurement_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('spectral_data_raw', 'response_count')
    op.alter_column('spectral_data_clean', 'intensity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('spectral_data_clean', 'wavelength_nm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('spectral_data_clean', 'measurement_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('observation_session', sa.Column('session_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('observation_session', sa.Column('orbit_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('observation_session', 'observation_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('observation_session', 'dataset_version_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('observation_session', 'notes')
    op.drop_column('observation_session', 'target_description')
    op.drop_column('observation_session', 'date_folder')
    op.add_column('observation_file_info', sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('observation_file_info', sa.Column('file_size_bytes', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('observation_file_info', sa.Column('md5_checksum', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'observation_file_info', type_='unique')
    op.alter_column('observation_file_info', 'observation_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('observation_file_info', 'file_info_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('observation_file_info', 'storage_path_clean')
    op.drop_column('observation_file_info', 'creation_datetime')
    op.drop_column('observation_file_info', 'xml_label_name')
    op.drop_column('observation_file_info', 'file_size_bytes_clean')
    op.drop_column('observation_file_info', 'file_size_bytes_raw')
    op.drop_column('observation_file_info', 'md5_checksum_clean')
    op.drop_column('observation_file_info', 'md5_checksum_raw')
    op.drop_column('observation_file_info', 'base_file_name')
    op.add_column('observation', sa.Column('xml_label_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'observation', type_='unique')
    op.drop_constraint(None, 'observation', type_='unique')
    op.alter_column('observation', 'processing_level',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('observation', 'information_model_version',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('observation', 'stop_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('observation', 'start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('observation', 'session_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('observation', 'observation_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('observation', 'purpose')
    op.drop_column('observation', 'pds_version_id')
    op.drop_column('observation', 'sub_index')
    op.drop_column('observation', 'observation_number')
    op.drop_column('observation', 'observation_code')
    op.drop_column('observation', 'logical_identifier')
    op.alter_column('nist_lines', 'wavelength_nm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('nist_lines', 'element',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('mission', 'launch_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('mission', 'organization',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('mission', 'mission_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('mission', 'mission_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('measurement_raw', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('measurement_raw', sa.Column('shot_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('measurement_raw', sa.Column('is_valid_plasma', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('measurement_raw', sa.Column('is_background', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('measurement_raw', 'file_info_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('measurement_raw', 'on_off_status')
    op.drop_column('measurement_raw', 'prr_hz')
    op.drop_column('measurement_raw', 'laser_pump_current_a')
    op.drop_column('measurement_raw', 'x_factor')
    op.drop_column('measurement_raw', 'number_of_pulses')
    op.drop_column('measurement_raw', 'delay_time_us')
    op.drop_column('measurement_raw', 'force_reset_status')
    op.drop_column('measurement_raw', 'measurement_type')
    op.drop_column('measurement_raw', 'operation_mode')
    op.drop_column('measurement_raw', 'measurement_count')
    op.drop_column('measurement_raw', 'time_utc')
    op.drop_column('measurement_raw', 'measurement_index')
    op.add_column('measurement_clean', sa.Column('shot_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('measurement_clean', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('measurement_clean', 'file_info_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('measurement_clean', 'on_off_status')
    op.drop_column('measurement_clean', 'prr_hz')
    op.drop_column('measurement_clean', 'laser_pump_current_a')
    op.drop_column('measurement_clean', 'x_factor')
    op.drop_column('measurement_clean', 'number_of_pulses')
    op.drop_column('measurement_clean', 'delay_time_us')
    op.drop_column('measurement_clean', 'force_reset_status')
    op.drop_column('measurement_clean', 'measurement_type')
    op.drop_column('measurement_clean', 'operation_mode')
    op.drop_column('measurement_clean', 'measurement_count')
    op.drop_column('measurement_clean', 'time_utc')
    op.drop_column('measurement_clean', 'measurement_index')
    op.add_column('instrument_spec_libs', sa.Column('calibration_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('instrument_spec_libs', sa.Column('spectral_channels', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'instrument_spec_libs', type_='unique')
    op.alter_column('instrument_spec_libs', 'detector_type',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('instrument_spec_libs', 'instrument_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('instrument_spec_libs', 'calibration_version')
    op.drop_column('instrument_spec_libs', 'pixel_count')
    op.drop_column('instrument_spec_libs', 'spectral_resolution_nm')
    op.drop_column('instrument_spec_libs', 'wavelength_max_nm')
    op.drop_column('instrument_spec_libs', 'wavelength_min_nm')
    op.add_column('instrument', sa.Column('resolution', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('instrument', sa.Column('wavelength_start', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('instrument', sa.Column('wavelength_end', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('instrument', 'instrument_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('instrument', 'instrument_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('instrument', 'mission_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('instrument', 'instrument_code')
    op.add_column('dataset_version', sa.Column('version_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('dataset_version', sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dataset_version', type_='unique')
    op.alter_column('dataset_version', 'processing_level',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('dataset_version', 'created_at')
    op.drop_column('dataset_version', 'released_at')
    op.drop_column('dataset_version', 'base_path')
    op.drop_column('dataset_version', 'data_level')
    op.drop_column('dataset_version', 'version_number')
    op.drop_column('dataset_version', 'version_label')
    # ### end Alembic commands ###
