"""Baseline schema

Revision ID: 778785292393
Revises: 
Create Date: 2026-06-28 17:03:11.539892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '778785292393'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), server_default='researcher', nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('interest', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=True)
    op.create_index(op.f('ix_app_users_username'), 'app_users', ['username'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('api_usage_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_bytes', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_log_created_at'), 'api_usage_log', ['created_at'], unique=False)
    op.add_column('dataset_version', sa.Column('version_code', sa.String(length=20), nullable=True))
    op.add_column('dataset_version', sa.Column('release_date', sa.Date(), nullable=True))
    op.alter_column('dataset_version', 'processing_level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('dataset_version', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('dataset_version_version_label_key'), 'dataset_version', type_='unique')
    op.drop_constraint(op.f('dataset_version_spec_id_fkey'), 'dataset_version', type_='foreignkey')
    op.create_foreign_key(None, 'dataset_version', 'instrument_spec_libs', ['spec_id'], ['spec_id'], ondelete='CASCADE')
    op.drop_column('dataset_version', 'created_at')
    op.drop_column('dataset_version', 'released_at')
    op.drop_column('dataset_version', 'version_number')
    op.drop_column('dataset_version', 'data_level')
    op.drop_column('dataset_version', 'version_label')
    op.drop_column('dataset_version', 'base_path')
    op.add_column('instrument', sa.Column('wavelength_start', sa.Float(), nullable=True))
    op.add_column('instrument', sa.Column('wavelength_end', sa.Float(), nullable=True))
    op.add_column('instrument', sa.Column('resolution', sa.String(length=50), nullable=True))
    op.alter_column('instrument', 'mission_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('instrument', 'instrument_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('instrument', 'instrument_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('instrument', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('instrument_mission_id_fkey'), 'instrument', type_='foreignkey')
    op.create_foreign_key(None, 'instrument', 'mission', ['mission_id'], ['mission_id'], ondelete='CASCADE')
    op.drop_column('instrument', 'instrument_code')
    op.add_column('instrument_spec_libs', sa.Column('spectral_channels', sa.Integer(), nullable=True))
    op.add_column('instrument_spec_libs', sa.Column('calibration_source', sa.String(), nullable=True))
    op.alter_column('instrument_spec_libs', 'instrument_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('instrument_spec_libs', 'detector_type',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_constraint(op.f('instrument_spec_libs_instrument_id_key'), 'instrument_spec_libs', type_='unique')
    op.drop_constraint(op.f('instrument_spec_libs_instrument_id_fkey'), 'instrument_spec_libs', type_='foreignkey')
    op.create_foreign_key(None, 'instrument_spec_libs', 'instrument', ['instrument_id'], ['instrument_id'], ondelete='CASCADE')
    op.drop_column('instrument_spec_libs', 'calibration_version')
    op.drop_column('instrument_spec_libs', 'wavelength_min_nm')
    op.drop_column('instrument_spec_libs', 'pixel_count')
    op.drop_column('instrument_spec_libs', 'spectral_resolution_nm')
    op.drop_column('instrument_spec_libs', 'wavelength_max_nm')
    op.add_column('measurement_clean', sa.Column('shot_number', sa.Integer(), nullable=True))
    op.add_column('measurement_clean', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('measurement_clean', 'file_info_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('measurement_clean', 'laser_fire_status',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint(op.f('measurement_clean_file_info_id_fkey'), 'measurement_clean', type_='foreignkey')
    op.create_foreign_key(None, 'measurement_clean', 'observation_file_info', ['file_info_id'], ['file_info_id'], ondelete='CASCADE')
    op.drop_column('measurement_clean', 'measurement_count')
    op.drop_column('measurement_clean', 'time_utc')
    op.drop_column('measurement_clean', 'measurement_type')
    op.drop_column('measurement_clean', 'force_reset_status')
    op.drop_column('measurement_clean', 'prr_hz')
    op.drop_column('measurement_clean', 'x_factor')
    op.drop_column('measurement_clean', 'measurement_index')
    op.drop_column('measurement_clean', 'operation_mode')
    op.drop_column('measurement_clean', 'number_of_pulses')
    op.drop_column('measurement_clean', 'on_off_status')
    op.drop_column('measurement_clean', 'delay_time_us')
    op.drop_column('measurement_clean', 'laser_pump_current_a')
    op.add_column('measurement_raw', sa.Column('shot_number', sa.Integer(), nullable=True))
    op.add_column('measurement_raw', sa.Column('is_valid_plasma', sa.Boolean(), nullable=True))
    op.add_column('measurement_raw', sa.Column('is_background', sa.Boolean(), nullable=True))
    op.add_column('measurement_raw', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('measurement_raw', 'file_info_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('measurement_raw', 'laser_fire_status',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint(op.f('measurement_raw_file_info_id_fkey'), 'measurement_raw', type_='foreignkey')
    op.create_foreign_key(None, 'measurement_raw', 'observation_file_info', ['file_info_id'], ['file_info_id'], ondelete='CASCADE')
    op.drop_column('measurement_raw', 'measurement_count')
    op.drop_column('measurement_raw', 'time_utc')
    op.drop_column('measurement_raw', 'measurement_type')
    op.drop_column('measurement_raw', 'force_reset_status')
    op.drop_column('measurement_raw', 'prr_hz')
    op.drop_column('measurement_raw', 'x_factor')
    op.drop_column('measurement_raw', 'measurement_index')
    op.drop_column('measurement_raw', 'operation_mode')
    op.drop_column('measurement_raw', 'number_of_pulses')
    op.drop_column('measurement_raw', 'on_off_status')
    op.drop_column('measurement_raw', 'delay_time_us')
    op.drop_column('measurement_raw', 'laser_pump_current_a')
    op.alter_column('mission', 'mission_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('mission', 'mission_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('mission', 'organization',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('mission', 'launch_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('mission', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('nist_lines', 'element',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('nist_lines', 'wavelength_nm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('idx_nist_lines_wavelength'), table_name='nist_lines')
    op.create_index(op.f('ix_nist_lines_wavelength_nm'), 'nist_lines', ['wavelength_nm'], unique=False)
    op.add_column('observation', sa.Column('xml_label_name', sa.String(length=255), nullable=True))
    op.alter_column('observation', 'observation_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('observation', 'session_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('observation', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('observation', 'stop_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('observation', 'information_model_version',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('observation', 'processing_level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_constraint(op.f('observation_logical_identifier_key'), 'observation', type_='unique')
    op.drop_constraint(op.f('observation_observation_code_key'), 'observation', type_='unique')
    op.drop_constraint(op.f('observation_session_id_fkey'), 'observation', type_='foreignkey')
    op.create_foreign_key(None, 'observation', 'observation_session', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.drop_column('observation', 'sub_index')
    op.drop_column('observation', 'purpose')
    op.drop_column('observation', 'observation_code')
    op.drop_column('observation', 'observation_number')
    op.drop_column('observation', 'pds_version_id')
    op.drop_column('observation', 'logical_identifier')
    op.add_column('observation_file_info', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('observation_file_info', sa.Column('file_size_bytes', sa.BigInteger(), nullable=True))
    op.add_column('observation_file_info', sa.Column('md5_checksum', sa.String(length=32), nullable=True))
    op.alter_column('observation_file_info', 'file_info_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('observation_file_info', 'observation_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
    op.drop_constraint(op.f('observation_file_info_observation_id_key'), 'observation_file_info', type_='unique')
    op.drop_constraint(op.f('fk_observation'), 'observation_file_info', type_='foreignkey')
    op.create_foreign_key(None, 'observation_file_info', 'observation', ['observation_id'], ['observation_id'], ondelete='CASCADE')
    op.drop_column('observation_file_info', 'md5_checksum_clean')
    op.drop_column('observation_file_info', 'creation_datetime')
    op.drop_column('observation_file_info', 'md5_checksum_raw')
    op.drop_column('observation_file_info', 'file_size_bytes_raw')
    op.drop_column('observation_file_info', 'base_file_name')
    op.drop_column('observation_file_info', 'file_size_bytes_clean')
    op.drop_column('observation_file_info', 'storage_path_clean')
    op.drop_column('observation_file_info', 'xml_label_name')
    op.add_column('observation_session', sa.Column('orbit_number', sa.Integer(), nullable=True))
    op.add_column('observation_session', sa.Column('session_type', sa.String(length=50), nullable=True))
    op.alter_column('observation_session', 'dataset_version_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('observation_session', 'observation_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(op.f('observation_session_dataset_version_id_observation_date_key'), 'observation_session', type_='unique')
    op.create_index(op.f('ix_observation_session_observation_date'), 'observation_session', ['observation_date'], unique=False)
    op.drop_constraint(op.f('observation_session_dataset_version_id_fkey'), 'observation_session', type_='foreignkey')
    op.create_foreign_key(None, 'observation_session', 'dataset_version', ['dataset_version_id'], ['dataset_version_id'], ondelete='CASCADE')
    op.drop_column('observation_session', 'notes')
    op.drop_column('observation_session', 'date_folder')
    op.drop_column('observation_session', 'target_description')
    op.alter_column('spectral_data_clean', 'measurement_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('spectral_data_clean', 'wavelength_nm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('spectral_data_clean', 'intensity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('idx_spectral_data_clean_measurement'), table_name='spectral_data_clean')
    op.create_index(op.f('ix_spectral_data_clean_measurement_id'), 'spectral_data_clean', ['measurement_id'], unique=False)
    op.create_index(op.f('ix_spectral_data_clean_wavelength_nm'), 'spectral_data_clean', ['wavelength_nm'], unique=False)
    op.drop_constraint(op.f('spectral_data_clean_measurement_id_fkey'), 'spectral_data_clean', type_='foreignkey')
    op.create_foreign_key(None, 'spectral_data_clean', 'measurement_clean', ['measurement_id'], ['measurement_id'], ondelete='CASCADE')
    op.add_column('spectral_data_raw', sa.Column('intensity', sa.Float(), nullable=True))
    op.alter_column('spectral_data_raw', 'measurement_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('spectral_data_raw', 'wavelength_nm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_spectral_data_raw_measurement_id'), 'spectral_data_raw', ['measurement_id'], unique=False)
    op.create_index(op.f('ix_spectral_data_raw_wavelength_nm'), 'spectral_data_raw', ['wavelength_nm'], unique=False)
    op.drop_constraint(op.f('spectral_data_raw_measurement_id_fkey'), 'spectral_data_raw', type_='foreignkey')
    op.create_foreign_key(None, 'spectral_data_raw', 'measurement_raw', ['measurement_id'], ['measurement_id'], ondelete='CASCADE')
    op.drop_column('spectral_data_raw', 'response_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spectral_data_raw', sa.Column('response_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'spectral_data_raw', type_='foreignkey')
    op.create_foreign_key(op.f('spectral_data_raw_measurement_id_fkey'), 'spectral_data_raw', 'measurement_raw', ['measurement_id'], ['measurement_id'])
    op.drop_index(op.f('ix_spectral_data_raw_wavelength_nm'), table_name='spectral_data_raw')
    op.drop_index(op.f('ix_spectral_data_raw_measurement_id'), table_name='spectral_data_raw')
    op.alter_column('spectral_data_raw', 'wavelength_nm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('spectral_data_raw', 'measurement_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('spectral_data_raw', 'intensity')
    op.drop_constraint(None, 'spectral_data_clean', type_='foreignkey')
    op.create_foreign_key(op.f('spectral_data_clean_measurement_id_fkey'), 'spectral_data_clean', 'measurement_clean', ['measurement_id'], ['measurement_id'])
    op.drop_index(op.f('ix_spectral_data_clean_wavelength_nm'), table_name='spectral_data_clean')
    op.drop_index(op.f('ix_spectral_data_clean_measurement_id'), table_name='spectral_data_clean')
    op.create_index(op.f('idx_spectral_data_clean_measurement'), 'spectral_data_clean', ['measurement_id'], unique=False)
    op.alter_column('spectral_data_clean', 'intensity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('spectral_data_clean', 'wavelength_nm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('spectral_data_clean', 'measurement_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('observation_session', sa.Column('target_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('observation_session', sa.Column('date_folder', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('observation_session', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'observation_session', type_='foreignkey')
    op.create_foreign_key(op.f('observation_session_dataset_version_id_fkey'), 'observation_session', 'dataset_version', ['dataset_version_id'], ['dataset_version_id'])
    op.drop_index(op.f('ix_observation_session_observation_date'), table_name='observation_session')
    op.create_unique_constraint(op.f('observation_session_dataset_version_id_observation_date_key'), 'observation_session', ['dataset_version_id', 'observation_date'])
    op.alter_column('observation_session', 'observation_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('observation_session', 'dataset_version_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('observation_session', 'session_type')
    op.drop_column('observation_session', 'orbit_number')
    op.add_column('observation_file_info', sa.Column('xml_label_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('observation_file_info', sa.Column('storage_path_clean', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('observation_file_info', sa.Column('file_size_bytes_clean', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('observation_file_info', sa.Column('base_file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('observation_file_info', sa.Column('file_size_bytes_raw', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('observation_file_info', sa.Column('md5_checksum_raw', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('observation_file_info', sa.Column('creation_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('observation_file_info', sa.Column('md5_checksum_clean', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'observation_file_info', type_='foreignkey')
    op.create_foreign_key(op.f('fk_observation'), 'observation_file_info', 'observation', ['observation_id'], ['observation_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_unique_constraint(op.f('observation_file_info_observation_id_key'), 'observation_file_info', ['observation_id'])
    op.alter_column('observation_file_info', 'observation_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('observation_file_info', 'file_info_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('observation_file_info', 'md5_checksum')
    op.drop_column('observation_file_info', 'file_size_bytes')
    op.drop_column('observation_file_info', 'file_name')
    op.add_column('observation', sa.Column('logical_identifier', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('observation', sa.Column('pds_version_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('observation', sa.Column('observation_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('observation', sa.Column('observation_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('observation', sa.Column('purpose', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('observation', sa.Column('sub_index', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'observation', type_='foreignkey')
    op.create_foreign_key(op.f('observation_session_id_fkey'), 'observation', 'observation_session', ['session_id'], ['session_id'])
    op.create_unique_constraint(op.f('observation_observation_code_key'), 'observation', ['observation_code'])
    op.create_unique_constraint(op.f('observation_logical_identifier_key'), 'observation', ['logical_identifier'])
    op.alter_column('observation', 'processing_level',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('observation', 'information_model_version',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('observation', 'stop_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('observation', 'start_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('observation', 'session_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('observation', 'observation_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('observation', 'xml_label_name')
    op.drop_index(op.f('ix_nist_lines_wavelength_nm'), table_name='nist_lines')
    op.create_index(op.f('idx_nist_lines_wavelength'), 'nist_lines', ['wavelength_nm'], unique=False)
    op.alter_column('nist_lines', 'wavelength_nm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('nist_lines', 'element',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('mission', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mission', 'launch_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('mission', 'organization',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('mission', 'mission_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('mission', 'mission_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.add_column('measurement_raw', sa.Column('laser_pump_current_a', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('measurement_raw', sa.Column('delay_time_us', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('measurement_raw', sa.Column('on_off_status', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('measurement_raw', sa.Column('number_of_pulses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('measurement_raw', sa.Column('operation_mode', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('measurement_raw', sa.Column('measurement_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('measurement_raw', sa.Column('x_factor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('measurement_raw', sa.Column('prr_hz', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('measurement_raw', sa.Column('force_reset_status', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('measurement_raw', sa.Column('measurement_type', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('measurement_raw', sa.Column('time_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('measurement_raw', sa.Column('measurement_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'measurement_raw', type_='foreignkey')
    op.create_foreign_key(op.f('measurement_raw_file_info_id_fkey'), 'measurement_raw', 'observation_file_info', ['file_info_id'], ['file_info_id'])
    op.alter_column('measurement_raw', 'laser_fire_status',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('measurement_raw', 'file_info_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('measurement_raw', 'created_at')
    op.drop_column('measurement_raw', 'is_background')
    op.drop_column('measurement_raw', 'is_valid_plasma')
    op.drop_column('measurement_raw', 'shot_number')
    op.add_column('measurement_clean', sa.Column('laser_pump_current_a', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('measurement_clean', sa.Column('delay_time_us', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('measurement_clean', sa.Column('on_off_status', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('measurement_clean', sa.Column('number_of_pulses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('measurement_clean', sa.Column('operation_mode', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('measurement_clean', sa.Column('measurement_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('measurement_clean', sa.Column('x_factor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('measurement_clean', sa.Column('prr_hz', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('measurement_clean', sa.Column('force_reset_status', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('measurement_clean', sa.Column('measurement_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('measurement_clean', sa.Column('time_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('measurement_clean', sa.Column('measurement_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'measurement_clean', type_='foreignkey')
    op.create_foreign_key(op.f('measurement_clean_file_info_id_fkey'), 'measurement_clean', 'observation_file_info', ['file_info_id'], ['file_info_id'])
    op.alter_column('measurement_clean', 'laser_fire_status',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('measurement_clean', 'file_info_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('measurement_clean', 'created_at')
    op.drop_column('measurement_clean', 'shot_number')
    op.add_column('instrument_spec_libs', sa.Column('wavelength_max_nm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('instrument_spec_libs', sa.Column('spectral_resolution_nm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('instrument_spec_libs', sa.Column('pixel_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('instrument_spec_libs', sa.Column('wavelength_min_nm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('instrument_spec_libs', sa.Column('calibration_version', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'instrument_spec_libs', type_='foreignkey')
    op.create_foreign_key(op.f('instrument_spec_libs_instrument_id_fkey'), 'instrument_spec_libs', 'instrument', ['instrument_id'], ['instrument_id'])
    op.create_unique_constraint(op.f('instrument_spec_libs_instrument_id_key'), 'instrument_spec_libs', ['instrument_id'])
    op.alter_column('instrument_spec_libs', 'detector_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('instrument_spec_libs', 'instrument_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('instrument_spec_libs', 'calibration_source')
    op.drop_column('instrument_spec_libs', 'spectral_channels')
    op.add_column('instrument', sa.Column('instrument_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'instrument', type_='foreignkey')
    op.create_foreign_key(op.f('instrument_mission_id_fkey'), 'instrument', 'mission', ['mission_id'], ['mission_id'])
    op.alter_column('instrument', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('instrument', 'instrument_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('instrument', 'instrument_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('instrument', 'mission_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('instrument', 'resolution')
    op.drop_column('instrument', 'wavelength_end')
    op.drop_column('instrument', 'wavelength_start')
    op.add_column('dataset_version', sa.Column('base_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('dataset_version', sa.Column('version_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('dataset_version', sa.Column('data_level', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('dataset_version', sa.Column('version_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('dataset_version', sa.Column('released_at', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('dataset_version', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dataset_version', type_='foreignkey')
    op.create_foreign_key(op.f('dataset_version_spec_id_fkey'), 'dataset_version', 'instrument_spec_libs', ['spec_id'], ['spec_id'])
    op.create_unique_constraint(op.f('dataset_version_version_label_key'), 'dataset_version', ['version_label'])
    op.alter_column('dataset_version', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('dataset_version', 'processing_level',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('dataset_version', 'release_date')
    op.drop_column('dataset_version', 'version_code')
    op.drop_index(op.f('ix_api_usage_log_created_at'), table_name='api_usage_log')
    op.drop_table('api_usage_log')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_app_users_username'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.drop_table('app_users')
    # ### end Alembic commands ###
